Repository redcraft-org/RedCraftWebsiteV3, pull requests merged in 2022-06, with the labels that each got.

#26 changed language standard
  public/available-languages.json
Labels: bug, enhancement

#27 Frontend
  .gitignore
  app/View/Components/section.php
  composer.json
  composer.lock
  package.json
  public/css/app.css
  public/css/home.css
  public/images/banner_empty.png
  public/images/red_white_grey_none_none_296.png
  public/js/app.js
  public/mix-manifest.json
  resources/sass/app.scss
  resources/sass/home.scss
  resources/views/components/section.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  resources/views/navigation-menu.blade.php
  resources/views/vendor/jetstream/components/button.blade.php
  resources/views/vendor/jetstream/components/nav-link.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tailwind.config.js
  webpack.mix.js
Labels: enhancement, dependencies

#28 Navbar
  app/Http/Requests/Player/PlayerCreateRequest.php
  app/Models/Player.php
  public/css/app.css
  resources/sass/app.scss
  resources/sass/navbar.scss
  resources/views/components/navbar-dropdown.blade.php
  resources/views/navigation-menu.blade.php
  resources/views/vendor/jetstream/components/nav-link.blade.php
  tailwind.config.js
Labels: enhancement

#24 created category seeder
  app/Models/Category.php
  app/Models/LocalizedCategory.php
  database/migrations/2021_12_10_225423_create_languages_table.php
  database/migrations/2021_12_10_225502_create_players_table.php
  database/seeders/CategorySeeder.php
  database/seeders/DatabaseSeeder.php
Labels: enhancement

#30 updated tailwind and others
  .gitignore
  package-lock.json
  package.json
  public/css/app.css
  public/css/home.css
  public/js/app.js
Labels: enhancement, dependencies, javascript

#34 Homepage
  .gitignore
  package-lock.json
  public/images/home/castle.jpg
  public/images/home/library.jpg
  public/images/home/people.png
  public/images/mc-img.jpeg
  resources/sass/app.scss
  resources/sass/button.scss
  resources/sass/home.scss
  resources/sass/pages/home.scss
  resources/sass/rebase.scss
  resources/views/components/home/about.blade.php
  resources/views/components/home/header.blade.php
  resources/views/components/home/news.blade.php
  resources/views/components/home/servers.blade.php
  resources/views/components/home/staff.blade.php
  resources/views/components/section.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  resources/views/vendor/jetstream/components/button.blade.php
  tailwind.config.js
  webpack.mix.js
Labels: enhancement

#35 Scroll reveal in about section
  package-lock.json
  package.json
  resources/js/app.js
  resources/views/components/home/about.blade.php
Labels: enhancement
